name: Auth service CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Auth Service Code
        uses: actions/checkout@v4

      - name: Debug Workspace Contents # <<--- THIS IS THE CRITICAL STEP
        run: |
          echo "GITHUB_WORKSPACE IS: ${{ github.workspace }}"
          echo "-------------------------------------------"
          echo "Current directory according to pwd: $(pwd)"
          echo "Listing GITHUB_WORKSPACE (${{ github.workspace }}) contents with ls -la:"
          ls -la ${{ github.workspace }}
          echo "-------------------------------------------"
          echo "Attempting to list package.json specifically from GITHUB_WORKSPACE:"
          ls -la ${{ github.workspace }}/package.json || echo "package.json NOT FOUND at GITHUB_WORKSPACE root"
          ls -la ${{ github.workspace }}/package-lock.json || echo "package-lock.json NOT FOUND at GITHUB_WORKSPACE root"
          echo "-------------------------------------------"

      - name: Checkout Auth Service Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
              ahmedthemagnificent/auth-service:latest
              ahmedthemagnificent/auth-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout K8s manifests repository
        uses: actions/checkout@v4
        with: 
          repository: Luk-Up/k8s
          path: k8s

      - name: Apply Kubernetes Manifests
        working-directory: ${{ github.workspace }}/k8s/auth-service # Windows paths
        run: |
         kubectl apply -f deployment.yaml
         kubectl apply -f service.yaml
         kubectl rollout restart deployment/auth-service



    